name: 量化自动爬虫
on:
  workflow_dispatch: # 手动一键运行
  schedule:
    - cron: '0 0 * * *' # UTC0点=国内早8点每日自动爬取
jobs:
  crawl_task:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许修改仓库文件
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
      - name: 配置Python3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: 安装依赖包
        run: pip install requests pandas akshare
      - name: 执行量化爬虫脚本
        run: python daily_spider.py
      - name: 提交更新后的data.json数据
        run: |
          git config --global user.name "量化自动机器人"
          git config --global user.email "robot@github.com"
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "自动更新行情数据" && git push)
